# Generated by Django 5.2.16 on 2026-07-27 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_protransport_master_fields'),
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='protransport_id',
            field=models.CharField(blank=True, db_index=True, help_text='Pro Transport trucks.id (stable external key). Do not match by unit_number.', max_length=64, null=True, unique=True, verbose_name='Pro Transport ID'),
        ),
        migrations.AddField(
            model_name='truck',
            name='source_is_active',
            field=models.BooleanField(blank=True, help_text='Active flag from Pro Transport; never drives RelayAssignment.', null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='current_driver',
            field=models.ForeignKey(blank=True, help_text='Derived cache from ACTIVE RelayAssignment; do not set from sync.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_trucks', to='drivers.driver'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('otr', 'OTR'), ('yard', 'Yard'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='available', help_text='Local Fleet Planner operational status (OTR/yard/maintenance).', max_length=20),
        ),
    ]
