# Generated by Django 5.2.16 on 2026-07-28 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_company_data_and_division'),
        ('trucks', '0002_protransport_master_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Pro Transport division (company_data via division_id).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to='companies.companydata'),
        ),
    ]
