# Generated by Django 5.2.16 on 2026-07-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='external_id',
            field=models.CharField(blank=True, help_text='External driver ID from your source system (used for import linking).', max_length=64, null=True, unique=True, verbose_name='Driver ID'),
        ),
    ]
