# Generated by Django 5.2.16 on 2026-07-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_rename_external_id_to_driver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated'), ('inactive', 'Inactive'), ('unknown', 'Unknown')], default='unknown', help_text='Employment status from Pro Transport master sync.', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.CharField(blank=True, db_index=True, help_text='Pro Transport drivers.id (stable external key). Do not match by name.', max_length=64, null=True, unique=True, verbose_name='Pro Transport ID'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('home_time', 'Home Time'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('terminated', 'Terminated')], default='pending', help_text='Local Fleet Planner operational status (OTR/home time workflow).', max_length=20),
        ),
    ]
