# Generated by Django 5.2.16 on 2026-07-08 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('relay', '0001_initial'),
        ('trucks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayStatusOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_start_date', models.DateField(blank=True, null=True)),
                ('expected_home_date', models.DateField(blank=True, null=True)),
                ('status_override', models.CharField(blank=True, choices=[('available', 'Available'), ('otr', 'OTR'), ('yard', 'Yard'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_overrides', to='drivers.driver')),
                ('next_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_driver_overrides', to='drivers.driver')),
                ('truck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_override', to='trucks.truck')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relay_overrides_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['truck__unit_number'],
            },
        ),
    ]
