# Generated by Django 5.2.16 on 2026-07-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0002_relaystatusoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='relaystatusoverride',
            name='next_driver_start_date',
            field=models.DateField(blank=True, help_text='When the next driver takes over this truck (start of their OTR cycle).', null=True),
        ),
    ]
