# Generated by Django 5.2.16 on 2026-07-15 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('relay', '0003_relaystatusoverride_next_driver_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverStatusPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('otr', 'OTR'), ('home_time', 'Home Time'), ('available', 'Available'), ('vacation', 'Vacation'), ('unavailable', 'Unavailable'), ('inactive', 'Inactive')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Exclusive end date when set ([start_date, end_date)).', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_status_periods', to='relay.relayassignment')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_periods', to='drivers.driver')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
    ]
