# Generated by Django 5.2.16 on 2026-07-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0005_home_time_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='relayassignment',
            name='start_date_is_estimated',
            field=models.BooleanField(default=False, help_text='True when start_date came from bootstrap cutover/default and still needs review.'),
        ),
    ]
