# Generated by Django 5.2.16 on 2026-07-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protransport_id', models.CharField(db_index=True, help_text='Pro Transport company_data.id (stable external key).', max_length=64, unique=True, verbose_name='Pro Transport ID')),
                ('name', models.CharField(help_text='Division / company name (PT division_name).', max_length=200)),
                ('dba', models.CharField(blank=True, max_length=200, verbose_name='DBA')),
                ('mc', models.CharField(blank=True, max_length=50, verbose_name='MC')),
                ('us_dot_no', models.CharField(blank=True, max_length=50, verbose_name='US DOT')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('mailing_city', models.CharField(blank=True, max_length=100)),
                ('mailing_state', models.CharField(blank=True, max_length=50)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company / division',
                'verbose_name_plural': 'Companies / divisions',
                'ordering': ['name'],
            },
        ),
    ]
